#Disables File Watcher. Used to automatically update config if its file has been modified.
disableConfigWatcher = false
#Shows an early loading screen for mod loading which improves the user experience with early feedback about mod loading.
earlyWindowControl = true
#Max threads for early initialization parallelism,  -1 is based on processor count
maxThreads = -1
#Enable NeoForge global version checking
versionCheck = true
#Enable synchronous OpenGL debug output and object labeling
debugOpenGl = false
#Default config path for servers
defaultConfigPath = "defaultconfigs"
#Disables Optimized DFU client-side - already disabled on servers
disableOptimizedDFU = true
#Early window provider
earlyWindowProvider = "fmlearlywindow"
#Early window width
earlyWindowWidth = 854
#Early window height
earlyWindowHeight = 480
#Early window starts maximized
earlyWindowMaximized = false
#Force a given theme-id to be used for the early loading screen
earlyLoadingScreenTheme = ""
#Define dependency overrides below
#Dependency overrides can be used to forcibly remove a dependency constraint from a mod or to force a mod to load AFTER another mod
#Using dependency overrides can cause issues. Use at your own risk.
#Example dependency override for the mod with the id 'targetMod': dependency constraints (incompatibility clauses or restrictive version ranges) against mod 'dep1' are removed, and the mod will now load after the mod 'dep2'
#dependencyOverrides.targetMod = ["-dep1", "+dep2"]
dependencyOverrides = {}
